spring.application.name=mediagent
server.port=8080

# AI/ML API
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mediagent
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update