spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

# AI API
groq.api.key=${GROQ_API_KEY}
groq.api.url=${GROQ_API_URL}

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

# Band API
band.api.url=${BAND_API_URL}
band.room.id=${BAND_ROOM_ID}
band.api.key=${BAND_API_KEY}