spring.application.name=mediagent
server.port=8080

# AI/ML API
aiml.api.key=27e2b30d372933be5a97fba8c97c9e2f
aiml.api.url=https://api.aimlapi.com/v1

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mediagent
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update